name: scipy2024-tutorial-thinking-in-arrays
channels:
  - conda-forge
dependencies:
  - aiohttp==3.9.5
  - awkward==2.6.5
  - fsspec==2024.6.1
  - git==2.45.2
  - hist==2.7.3
  - jax==0.4.27
  - jaxlib==0.4.25
  - jupyterlab==4.2.3
  - jupyterlab-deck==0.2.0
  - jupyterlab-mathjax3==4.3.0
  - matplotlib==3.9.0
  - mplhep==0.3.50
  - numba==0.60.0
  - numexpr==2.10.0
  - numpy==1.26.4
  - pandas==2.2.2
  - pyarrow==16.1.0
  - python==3.11.4
  - requests==2.32.3
  - scikit-learn==1.5.1
  - scipy==1.11.1
  - tbb==2021.12.0
