name: 2023-07-11-scipy-tutorial-advanced-numpy
channels:
  - conda-forge
dependencies:
  - aiohttp==3.8.4
  - awkward==2.2.2
  - fsspec==2023.6.0
  - git==2.41.0
  - hist==2.6.3
  - jax==0.4.12
  - jaxlib==0.4.12
  - jupyterlab==3.6.4
  - jupyterlab-deck==0.1.3
  - jupyterlab-mathjax3==4.3.0
  - matplotlib==3.7.1
  - mplhep==0.3.28
  - numba==0.57.0
  - numexpr==2.8.4
  - numpy==1.24.3
  - pandas==2.0.2
  - pyarrow==12.0.0
  - python==3.11.4
  - requests==2.31.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - tbb==2021.9.0
