name: 2023-07-11-scipy-tutorial-advanced-numpy
channels:
  - conda-forge
dependencies:
  - awkward
  - fsspec
  - git
  - hist
  - jax
  - jaxlib
  - jupyterlab
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - matplotlib
  - mplhep
  - numba
  - numexpr
  - numpy
  - pandas
  - pyarrow
  - python
  - scikit-learn
  - scipy
